### ISSUE TITLE
'PathObject' object has no attribute 'text' 

### ISSUE THREAD

**Issue by matthieu-lapeyre** [IndiePython/nodezator#30]
Hello,

I got this error immediately after trying clicking on "new file" or "open file" (on the splash screen or menu bar).
Version 1.12 release candidate.

```bash
python3 -m nodezator

Traceback (most recent call last):
  File "[...]/nodezator/fileman/dirpanel/main.py", line 351, in update_path_objs_appearance
    try: index = self.selectable_paths.index(
ValueError: None is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "[...]/nodezator/__main__.py", line 113, in <module>
    main(args.filepath)
  File "[...]/nodezator/__main__.py", line 72, in main
    run_app(filepath)
  File "[...]/nodezator/mainloop.py", line 208, in run_app
    raise err
  File "[...]/nodezator/mainloop.py", line 97, in run_app
    loop_holder.handle_input()
  File "[...]/nodezator/splashscreen/op.py", line 134, in handle_input
    self.on_mouse_release(event)
  File "[...]/nodezator/splashscreen/op.py", line 175, in on_mouse_action
    else: method(event)
  File "[...]/nodezator/ourstdlibs/behaviour.py", line 559, in execute
    return func()
  File "[...]/nodezator/winman/fileop.py", line 78, in new
    paths = create_path(caption=NEW_FILE_CAPTION)
  File "[...]/nodezator/fileman/op.py", line 117, in browse_paths
    self.dir_panel.load_current_dir_contents()
  File "[...]/nodezator/fileman/dirpanel/loadop.py", line 93, in load_current_dir_contents
    self.update_path_objs_appearance()
  File "[...]/nodezator/fileman/dirpanel/main.py", line 367, in update_path_objs_appearance
    if path_obj.text == PATH_OBJ_PARENT_TEXT:
AttributeError: 'PathObject' object has no attribute 'text'
```

**Comment by KennedyRichard** [comment]
Hello, Mr. Lapeyre.

Thank you for your report. I'm sorry that you are experiencing this inconvenience. I assume this error is making the app to crash, right? Bugs that cause the app to crash are high priority, so I'll tend to it right away.

Also, just to be clear, when you said "Version 1.12" you meant 1.1.2, right?

**Comment by matthieu-lapeyre** [comment]
Yes and Yes :)

**Comment by KennedyRichard** [comment]
Mr. Lapeyre, I just pushed a new patch that should solve this bug. Would you please update nodezator to the next version (1.1.3) and see if the problem persists?

Depending on your system, updating is just a matter of running `pip install --upgrade nodezator` or `pip3 install --upgrade nodezator`.

**Comment by matthieu-lapeyre** [comment]
no more problem, thanks

**Comment by KennedyRichard** [comment]
Neat! I still got it!

![kermit dancing](https://media.giphy.com/media/1YcLOSW6JCNdsfSr5E/giphy.gif)

Closing the issue now. Have a nice weekend.
