### ISSUE TITLE
Crash when clicking on read_text_file when no file is selected

### ISSUE THREAD

**Issue by Banbury** [IndiePython/nodezator#40]
Environment:
Windows 7
Python 3.9 (backport)

Steps to reproduce:
* Open a new file
* Add a read_text_file node
* Click on the file preview

The application crashes to the desktop.

Error message:
```
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\nodezator\nodezator\__main__.py", line 95, in <module>
    parse_args_and_execute_main()
  File "d:\nodezator\nodezator\__main__.py", line 89, in parse_args_and_execute_
main
    main(filepath)
  File "d:\nodezator\nodezator\__main__.py", line 56, in main
    run_app(filepath)
  File "d:\nodezator\nodezator\mainloop.py", line 209, in run_app
    raise err
  File "d:\nodezator\nodezator\mainloop.py", line 98, in run_app
    loop_holder.handle_input()
  File "d:\nodezator\nodezator\ourstdlibs\collections\general.py", line 20, in _
_call__
    item()
  File "d:\nodezator\nodezator\winman\states\loadedfile.py", line 106, in loaded
_file_event_handling
    self.loaded_file_on_mouse_release(event)
  File "d:\nodezator\nodezator\winman\states\loadedfile.py", line 506, in loaded
_file_on_mouse_release
    obj.on_mouse_release(event)
  File "d:\nodezator\nodezator\graphman\callablenode\vizop\main.py", line 87, in
 on_mouse_action
    method(event)
  File "d:\nodezator\nodezator\widget\pathpreview\base.py", line 362, in on_mous
e_release
    self.preview_paths()
  File "d:\nodezator\nodezator\widget\pathpreview\text.py", line 140, in preview
_paths
    text = path.read_text(encoding="utf-8")
  File "C:\Python39\lib\pathlib.py", line 1266, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Python39\lib\pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Python39\lib\pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '.'
```
Some form of error handling would be nice. Ideally an application should never crash to the desktop.

**Comment by dh1ao** [comment]
It maybe a windows problem?
Under Linux it works
![nodez](https://user-images.githubusercontent.com/10810209/227251412-eed91849-d92d-4fc4-bb0c-f853f8073e1d.png)

**Comment by KennedyRichard** [comment]
Mr. Banbury,

Thank you for your detailed bug report, it is much appreciated.

Just wanted to let you know I'm aware of your issue and will solve it asap.

ETA for a solution, including its upload to PyPI, is a couple of days. It may be much earlier, though, since I suspect this problem will only take a few minutes to solve.

Peace

**Comment by KennedyRichard** [comment]
Also, I forgot to thank you, Mr. @dh1ao, for taking the time to verify it for me on linux. This donation of time is very selfless on your part. Thank you a lot!

**Comment by KennedyRichard** [comment]
Mr. Banbury,

Just fixed the bug. The new `1.3.11` version with the bugfix was already pushed to github and uploaded to PyPI. To access this latest version with the bugfix just upgrade your installation with the command:

```pip install --upgrade nodezator```

Could you please, confirm that the problem was fixed in your machine so that I can close this issue?

When following the steps you described to reproduce the error, instead of the app crashing on you, a dialogue should appear communicating the error, just like in the image below:

![error_dialogue](https://user-images.githubusercontent.com/18728298/227636653-5c8908bf-2248-42a3-83fc-637e8298a29e.png)

**Comment by KennedyRichard** [comment]
Mr. Banbury,

Since the issue is already solved (the bug is fixed) and we waited for your confirmation for 10 calendar days already, I'm closing the issue now.

Don't worry about not having replied. We just ask for confirmation to make sure the changes really took effect on the user's end.

If users don't reply, I just assume they were too busy at the time or had their reasons.

Peace.
